version: '3'

services:
    dbapp:
        image: mysql:5
        restart: always
        volumes:
            - ./db-volume:/var/lib/mysql
        env_file:
            - moodle_variables.env
        networks:
            - backendDB
        deploy:
            replicas: 1
            restart_policy:
                condition: any
    moodleapp:
#        image: jhardison/moodle:latest
        image: dhub.lex.lan:5000/app/moodle:lexema
        links:
            - dbapp:DB
        depends_on: 
            - dbapp
        restart: always
        volumes:
            - ./moodleapp-data:/var/moodledata
            - ./moodleapp-mod:/var/www/html/mod
        ports:
            - 8081:80
            - 4438:443
        env_file:
            - moodle_variables.env
        networks:
            - backendDB
#            - frontendWEB
            - proxy
        deploy:
            replicas: 1
            restart_policy:
                condition: any            

#volumes: 
#    db-volume:
#    moodleapp-data:
networks:
  proxy:
    external: true
  default:
    ipam:
      config:
        - subnet: 172.29.0.0/24
  backendDB:
    ipam:
      config:
        - subnet: 172.29.1.0/24

  frontendWEB:
    ipam:
      config:
        - subnet: 172.29.2.0/24

